"""
failure_taxonomy.py — Comprehensive 25 Payment Failure Taxonomy

Mirrors production-grade payment failure payloads and error semantics (Razorpay standard).
Provides authoritative metadata for:
- Payment Gateway simulation (authentic error payloads)
- Risk Engine (base risk, recovery probability, strategies)
- Multi-Agent Intelligence (Detection, Root Cause diagnosis, Strategy formulation)
"""

from typing import Dict, Any, Optional, List, Union

FAILURE_TAXONOMY: Dict[str, Dict[str, Any]] = {
    "BANK_TIMEOUT": {
        "id": "BANK_TIMEOUT",
        "name": "Payment Timeout",
        "category": "TECHNICAL_INFRASTRUCTURE",
        "source": "gateway",
        "step": "payment_authorization",
        "code": "GATEWAY_ERROR",
        "reason": "gateway_timeout",
        "description": "Payment authorization timed out waiting for upstream bank switch response.",
        "base_risk": 75,
        "base_prob": 0.90,
        "strategy": "Delayed Retry",
        "retry_delay_seconds": 900,
        "alternate_method": "CARD",
        "agent_diagnosis": "Issuing bank switch unresponsive during authorization window (>15s timeout).",
        "agent_action": "Transient bank switch outage. Optimal recovery achieved via off-peak delayed retry after 15 minutes.",
    },
    "CARD_DECLINED": {
        "id": "CARD_DECLINED",
        "name": "Card Declined",
        "category": "FINANCIAL_AUTH",
        "source": "card",
        "step": "payment_authorization",
        "code": "BAD_REQUEST_ERROR",
        "reason": "card_declined",
        "description": "Card issuer declined transaction due to card limit or 3DS challenge drop.",
        "base_risk": 85,
        "base_prob": 0.65,
        "strategy": "Smart Alternative Link",
        "retry_delay_seconds": 0,
        "alternate_method": "UPI",
        "agent_diagnosis": "Card issuing institution declined transaction due to card limit, international restriction, or 3DS challenge drop.",
        "agent_action": "Direct card re-attempt has low success. Sending one-click smart recovery link with UPI and NetBanking options.",
    },
    "NETWORK_ERROR": {
        "id": "NETWORK_ERROR",
        "name": "Network Failure",
        "category": "TECHNICAL_NETWORK",
        "source": "network",
        "step": "payment_authorization",
        "code": "GATEWAY_ERROR",
        "reason": "network_connection_reset",
        "description": "TCP connection reset or packet drop occurred during data exchange.",
        "base_risk": 60,
        "base_prob": 0.90,
        "strategy": "Instant Network Retry",
        "retry_delay_seconds": 10,
        "alternate_method": "CARD",
        "agent_diagnosis": "Transient network socket drop during TLS handshake with payment network.",
        "agent_action": "Dispatched immediate idempotent retry with zero customer intervention required.",
    },
    "INSUFFICIENT_FUNDS": {
        "id": "INSUFFICIENT_FUNDS",
        "name": "Insufficient Funds",
        "category": "FINANCIAL_LIQUIDITY",
        "source": "customer",
        "step": "payment_authorization",
        "code": "BAD_REQUEST_ERROR",
        "reason": "insufficient_funds",
        "description": "Payment failed due to insufficient funds in customer account or credit limit exhaustion.",
        "base_risk": 65,
        "base_prob": 0.75,
        "strategy": "Delayed Retry + Balance Nudge",
        "retry_delay_seconds": 86400,  # 24h
        "alternate_method": "UPI",
        "agent_diagnosis": "Customer liquidity deficit at issuing institution. Account active but balance below transaction requirement.",
        "agent_action": "Dispatched gentle balance notification via WhatsApp/SMS with delayed retry scheduled for next morning.",
    },
    "BANK_DECLINED": {
        "id": "BANK_DECLINED",
        "name": "Bank Declined",
        "category": "Bank",
        "source": "bank",
        "step": "payment_authorization",
        "code": "GATEWAY_ERROR",
        "reason": "payment_declined_by_bank",
        "description": "The customer's issuing bank declined the transaction due to policy or risk rules.",
        "base_risk": 82,
        "base_prob": 0.62,
        "strategy": "Alternative Rail / Switch to UPI",
        "retry_delay_seconds": 1800,
        "alternate_method": "UPI",
        "agent_diagnosis": "Issuing bank declined debit. Likely policy restriction on card type or commercial transaction limit.",
        "agent_action": "Generated instant dynamic Smart Link offering alternative banking rails and UPI Intent.",
    },
    "CARD_EXPIRED": {
        "id": "CARD_EXPIRED",
        "name": "Card Expired",
        "category": "Card",
        "source": "card",
        "step": "payment_initiation",
        "code": "BAD_REQUEST_ERROR",
        "reason": "card_expired",
        "description": "The card expiration date provided has elapsed or is invalid.",
        "base_risk": 78,
        "base_prob": 0.85,
        "strategy": "Update Card Details / One-Click UPI Link",
        "retry_delay_seconds": 0,
        "alternate_method": "UPI",
        "agent_diagnosis": "Card validity elapsed. Card token invalidated by card network (Visa/Mastercard tokenization service).",
        "agent_action": "Dispatched seamless 1-click update token prompt with instant fallback to UPI autopay.",
    },
    "CARD_BLOCKED": {
        "id": "CARD_BLOCKED",
        "name": "Card Blocked",
        "category": "Card/Bank",
        "source": "bank",
        "step": "payment_authorization",
        "code": "GATEWAY_ERROR",
        "reason": "card_blocked",
        "description": "Card is permanently or temporarily blocked by the issuer for security or administrative reasons.",
        "base_risk": 88,
        "base_prob": 0.55,
        "strategy": "Alternative Payment Method (UPI/NetBanking)",
        "retry_delay_seconds": 0,
        "alternate_method": "NET_BANKING",
        "agent_diagnosis": "Card flagged by issuer security switch (hotlisted/restricted). Direct re-attempts will continually fail.",
        "agent_action": "Suppressed card retry channel; routed recovery through verified Net Banking and UPI rails.",
    },
    "INCORRECT_CARD_DETAILS": {
        "id": "INCORRECT_CARD_DETAILS",
        "name": "Incorrect Card Details",
        "category": "Customer",
        "source": "customer",
        "step": "payment_initiation",
        "code": "BAD_REQUEST_ERROR",
        "reason": "invalid_card_details",
        "description": "Customer provided invalid card number, CVV, or cardholder name mismatch.",
        "base_risk": 60,
        "base_prob": 0.88,
        "strategy": "Card Details Re-prompt Modal",
        "retry_delay_seconds": 0,
        "alternate_method": "CARD",
        "agent_diagnosis": "Luhn algorithm checksum failure or CVV verification mismatch during pre-auth validation.",
        "agent_action": "Dispatched instant in-session card re-entry modal with auto-detection of card brand.",
    },
    "INVALID_UPI_ID": {
        "id": "INVALID_UPI_ID",
        "name": "Invalid UPI ID / VPA",
        "category": "UPI",
        "source": "customer",
        "step": "payment_initiation",
        "code": "BAD_REQUEST_ERROR",
        "reason": "invalid_vpa",
        "description": "The Virtual Payment Address (VPA) is invalid, inactive, or could not be resolved by NPCI.",
        "base_risk": 58,
        "base_prob": 0.90,
        "strategy": "UPI VPA Auto-Correction / Dynamic QR Code",
        "retry_delay_seconds": 0,
        "alternate_method": "UPI_QR",
        "agent_diagnosis": "NPCI central mapper returned VPA resolution failure. Typos detected in handle domain.",
        "agent_action": "Generated dynamic BharatQR / UPI QR code on checkout screen bypasses manual VPA entry.",
    },
    "UPI_PAYMENT_DECLINED": {
        "id": "UPI_PAYMENT_DECLINED",
        "name": "UPI Payment Declined",
        "category": "UPI/Bank",
        "source": "bank",
        "step": "payment_authorization",
        "code": "GATEWAY_ERROR",
        "reason": "upi_mpin_or_bank_declined",
        "description": "UPI transaction declined by customer's bank app (e.g. incorrect MPIN or debit freeze).",
        "base_risk": 70,
        "base_prob": 0.72,
        "strategy": "UPI Intent Re-trigger / Alternative App",
        "retry_delay_seconds": 300,
        "alternate_method": "UPI_INTENT",
        "agent_diagnosis": "Remitter bank declined authorization during MPIN verification on PSP app.",
        "agent_action": "Triggered direct UPI Intent deep-link to alternate PSP app (Google Pay / PhonePe / Paytm).",
    },
    "UPI_TIMEOUT": {
        "id": "UPI_TIMEOUT",
        "name": "UPI Timeout",
        "category": "UPI/Network",
        "source": "network",
        "step": "payment_authorization",
        "code": "GATEWAY_ERROR",
        "reason": "upi_transaction_timeout",
        "description": "UPI switch failed to respond within permissible time window.",
        "base_risk": 74,
        "base_prob": 0.85,
        "strategy": "Dynamic UPI Push with Extended Window",
        "retry_delay_seconds": 600,
        "alternate_method": "UPI",
        "agent_diagnosis": "NPCI UPI switch latency exceeding 45-second gateway timeout threshold.",
        "agent_action": "Scheduled off-peak retry and sent real-time push notification with 15-minute active window.",
    },
    "UPI_COLLECT_REQUEST_EXPIRED": {
        "id": "UPI_COLLECT_REQUEST_EXPIRED",
        "name": "UPI Collect Request Expired",
        "category": "UPI",
        "source": "customer",
        "step": "payment_authorization",
        "code": "BAD_REQUEST_ERROR",
        "reason": "upi_collect_expired",
        "description": "Customer did not open their UPI app to approve the collect request before expiration.",
        "base_risk": 68,
        "base_prob": 0.76,
        "strategy": "Fresh UPI Collect Notification",
        "retry_delay_seconds": 120,
        "alternate_method": "UPI_INTENT",
        "agent_diagnosis": "Customer notification latency or inattention; collect request TTL (5 min) lapsed without approval.",
        "agent_action": "Dispatched WhatsApp notification with instant approval deeplink to customer's active device.",
    },
    "CUSTOMER_CANCELLED": {
        "id": "CUSTOMER_CANCELLED",
        "name": "Customer Cancelled",
        "category": "Customer",
        "source": "customer",
        "step": "payment_authentication",
        "code": "BAD_REQUEST_ERROR",
        "reason": "payment_cancelled_by_user",
        "description": "Customer voluntarily closed the payment modal or clicked 'Cancel' on the 3DS page.",
        "base_risk": 72,
        "base_prob": 0.65,
        "strategy": "Abandoned Cart Recovery Link",
        "retry_delay_seconds": 1800,
        "alternate_method": "SMART_LINK",
        "agent_diagnosis": "User intent abandonment during checkout flow (price check, hesitation, or UX friction).",
        "agent_action": "Dispatched personalized cart recovery link with 5% limited-time incentive via email & SMS.",
    },
    "PAYMENT_TIMEOUT": {
        "id": "PAYMENT_TIMEOUT",
        "name": "Payment Timeout",
        "category": "Network/Gateway",
        "source": "gateway",
        "step": "payment_authorization",
        "code": "GATEWAY_ERROR",
        "reason": "gateway_timeout",
        "description": "Payment authorization timed out waiting for upstream acquiring bank response.",
        "base_risk": 75,
        "base_prob": 0.90,
        "strategy": "Asynchronous Status Poll & Delayed Retry",
        "retry_delay_seconds": 900,
        "alternate_method": "CARD",
        "agent_diagnosis": "Asynchronous communication breakdown between payment aggregator and card network switch.",
        "agent_action": "Initiated background reconciliation poll; scheduled automatic retry on alternate gateway route.",
    },
    "BANK_DOWNTIME": {
        "id": "BANK_DOWNTIME",
        "name": "Bank Downtime",
        "category": "Bank",
        "source": "bank",
        "step": "payment_authorization",
        "code": "GATEWAY_ERROR",
        "reason": "bank_downtime",
        "description": "Issuing or partner bank is experiencing temporary technical degradation or maintenance.",
        "base_risk": 84,
        "base_prob": 0.88,
        "strategy": "Dynamic Rail Failover to Secondary Acquirer",
        "retry_delay_seconds": 1800,
        "alternate_method": "UPI",
        "agent_diagnosis": "Bank Core Banking System (CBS) downtime detected via network health ping telemetry.",
        "agent_action": "Automatically rerouted transaction to secondary acquirer and prompt customer to use alternate bank rail.",
    },
    "GATEWAY_ERROR": {
        "id": "GATEWAY_ERROR",
        "name": "Gateway Error",
        "category": "Gateway",
        "source": "gateway",
        "step": "payment_authorization",
        "code": "GATEWAY_ERROR",
        "reason": "gateway_processing_error",
        "description": "Payment gateway encountered an unexpected internal error during processing.",
        "base_risk": 70,
        "base_prob": 0.94,
        "strategy": "Instant Acquirer Route Failover",
        "retry_delay_seconds": 15,
        "alternate_method": "CARD",
        "agent_diagnosis": "Aggregator routing switch returned 502/504 Bad Gateway from primary terminal.",
        "agent_action": "Executed sub-second dynamic rail failover across active secondary payment gateway.",
    },
    "NETWORK_FAILURE": {
        "id": "NETWORK_FAILURE",
        "name": "Network Failure",
        "category": "Network",
        "source": "network",
        "step": "payment_authorization",
        "code": "GATEWAY_ERROR",
        "reason": "network_connection_reset",
        "description": "TCP connection reset or packet drop occurred during data exchange with payment network.",
        "base_risk": 60,
        "base_prob": 0.92,
        "strategy": "Instant Idempotent Network Retry",
        "retry_delay_seconds": 10,
        "alternate_method": "CARD",
        "agent_diagnosis": "Transient network socket drop during TLS handshake with payment network.",
        "agent_action": "Dispatched immediate idempotent retry with zero customer intervention required.",
    },
    "TECHNICAL_ERROR": {
        "id": "TECHNICAL_ERROR",
        "name": "Technical Error",
        "category": "System",
        "source": "gateway",
        "step": "payment_authorization",
        "code": "SERVER_ERROR",
        "reason": "unexpected_system_error",
        "description": "An unexpected technical error occurred in the payment processing pipeline.",
        "base_risk": 65,
        "base_prob": 0.88,
        "strategy": "Idempotent Safe Re-attempt",
        "retry_delay_seconds": 60,
        "alternate_method": "CARD",
        "agent_diagnosis": "Internal worker pool queue timeout during signature verification.",
        "agent_action": "Safe idempotent replay initiated through isolated processing pipeline.",
    },
    "PAYMENT_METHOD_UNAVAILABLE": {
        "id": "PAYMENT_METHOD_UNAVAILABLE",
        "name": "Payment Method Unavailable",
        "category": "Payment Method",
        "source": "gateway",
        "step": "payment_initiation",
        "code": "BAD_REQUEST_ERROR",
        "reason": "payment_method_disabled",
        "description": "Selected payment method is temporarily disabled or unavailable for this merchant/currency.",
        "base_risk": 62,
        "base_prob": 0.82,
        "strategy": "Smart Alternative Method Recommendation",
        "retry_delay_seconds": 0,
        "alternate_method": "UPI",
        "agent_diagnosis": "Payment rail taken offline for maintenance by aggregator.",
        "agent_action": "Prompted customer with 1-click checkout options on high-success UPI & card rails.",
    },
    "LIMIT_EXCEEDED": {
        "id": "LIMIT_EXCEEDED",
        "name": "Limit Exceeded",
        "category": "Bank/Customer",
        "source": "bank",
        "step": "payment_authorization",
        "code": "BAD_REQUEST_ERROR",
        "reason": "transaction_limit_exceeded",
        "description": "Transaction amount exceeds per-transaction or daily limit set by bank or customer.",
        "base_risk": 80,
        "base_prob": 0.60,
        "strategy": "Split Payment / Higher Limit Rail",
        "retry_delay_seconds": 0,
        "alternate_method": "NET_BANKING",
        "agent_diagnosis": "Transaction breached RBI/bank per-day UPI (₹1L) or card online spend ceiling.",
        "agent_action": "Offered 2-part split payment or direct Corporate Net Banking with ₹10L limit.",
    },
    "AUTHENTICATION_FAILED": {
        "id": "AUTHENTICATION_FAILED",
        "name": "Authentication Failed",
        "category": "Customer/Bank",
        "source": "customer",
        "step": "payment_authentication",
        "code": "BAD_REQUEST_ERROR",
        "reason": "3ds_authentication_failed",
        "description": "Customer failed 3DS authentication (incorrect OTP or biometric verification timed out).",
        "base_risk": 70,
        "base_prob": 0.74,
        "strategy": "3DS OTP Re-prompt via SMS/WhatsApp",
        "retry_delay_seconds": 60,
        "alternate_method": "UPI",
        "agent_diagnosis": "OTP entry mismatch or 3DS session timeout on bank Access Control Server (ACS).",
        "agent_action": "Triggered instant biometric 3DS 2.0 re-prompt and backup WhatsApp OTP verification.",
    },
    "MANDATE_FAILED": {
        "id": "MANDATE_FAILED",
        "name": "Mandate Failed",
        "category": "RECURRING_MANDATE",
        "source": "bank",
        "step": "payment_authorization",
        "code": "GATEWAY_ERROR",
        "reason": "e_mandate_execution_failed",
        "description": "Recurring e-mandate execution failed at destination bank.",
        "base_risk": 75,
        "base_prob": 0.70,
        "strategy": "Mandate Batch Re-presentation",
        "retry_delay_seconds": 3600,
        "alternate_method": "UPI_AUTOPAY",
        "agent_diagnosis": "Pre-debit notification window or e-mandate mandate ID unrecognized by destination bank.",
        "agent_action": "Rescheduled mandate re-presentation in next clearing cycle adhering to RBI recurring rules.",
    },
    "MANDATE_REVOKED": {
        "id": "MANDATE_REVOKED",
        "name": "Mandate Cancelled/Revoked",
        "category": "Subscription",
        "source": "customer",
        "step": "payment_authorization",
        "code": "BAD_REQUEST_ERROR",
        "reason": "mandate_cancelled_by_customer",
        "description": "Customer or issuing bank cancelled or revoked the recurring payment mandate.",
        "base_risk": 90,
        "base_prob": 0.45,
        "strategy": "New E-Mandate Authorization Link",
        "retry_delay_seconds": 0,
        "alternate_method": "UPI_AUTOPAY",
        "agent_diagnosis": "Mandate state marked REVOKED in NPCI e-Mandate registry.",
        "agent_action": "Dispatched email & SMS with 1-click re-authorization link to register fresh mandate.",
    },
    "RECURRING_PAYMENT_FAILED": {
        "id": "RECURRING_PAYMENT_FAILED",
        "name": "Recurring Payment Failed",
        "category": "Subscription",
        "source": "bank",
        "step": "payment_authorization",
        "code": "GATEWAY_ERROR",
        "reason": "subscription_charge_failed",
        "description": "Automated recurring subscription charge failed due to balance or bank lock.",
        "base_risk": 76,
        "base_prob": 0.68,
        "strategy": "Grace Period Retry & Customer Alert",
        "retry_delay_seconds": 14400,  # 4h
        "alternate_method": "CARD",
        "agent_diagnosis": "Scheduled debit run rejected during off-peak processing cycle.",
        "agent_action": "Applied 3-day grace period; scheduled smart retries aligned with typical salary credit days.",
    },
    "DUPLICATE_PAYMENT_ATTEMPT": {
        "id": "DUPLICATE_PAYMENT_ATTEMPT",
        "name": "Duplicate Payment Attempt",
        "category": "System",
        "source": "system",
        "step": "payment_initiation",
        "code": "BAD_REQUEST_ERROR",
        "reason": "duplicate_idempotency_key",
        "description": "A payment with this idempotency key or order ID has already been initiated or processed.",
        "base_risk": 50,
        "base_prob": 0.95,
        "strategy": "Deduplication & Auto-Refund Safeguard",
        "retry_delay_seconds": 0,
        "alternate_method": "CARD",
        "agent_diagnosis": "Double-click submission by customer; duplicate idempotency key detected.",
        "agent_action": "Safely reconciled duplicate request; verified first successful charge and prevented double-billing.",
    },
    "RISK_FRAUD_DECLINE": {
        "id": "RISK_FRAUD_DECLINE",
        "name": "Risk/Fraud Decline",
        "category": "Risk",
        "source": "risk",
        "step": "payment_authorization",
        "code": "BAD_REQUEST_ERROR",
        "reason": "fraud_security_trigger",
        "description": "Transaction blocked by risk engine due to unusual geolocation, velocity, or fraud rules.",
        "base_risk": 95,
        "base_prob": 0.35,
        "strategy": "Enhanced 3DS Step-Up Verification",
        "retry_delay_seconds": 0,
        "alternate_method": "NET_BANKING",
        "agent_diagnosis": "High velocity or anomalous device IP trigger detected by internal fraud shield.",
        "agent_action": "Flagged for bounded compliance review. Automated recovery halted to prevent fraud exposure; escalated for merchant manual review.",
    },
    "LATE_AUTHORIZATION": {
        "id": "LATE_AUTHORIZATION",
        "name": "Late Authorization",
        "category": "Network/Gateway/Bank",
        "source": "gateway",
        "step": "payment_authorization",
        "code": "GATEWAY_ERROR",
        "reason": "late_authorization_received",
        "description": "Payment initially appeared failed/timeout, but late authorization arrived from bank after timeout.",
        "base_risk": 40,
        "base_prob": 0.98,
        "strategy": "Asynchronous Webhook Re-query",
        "retry_delay_seconds": 0,
        "alternate_method": "CARD",
        "agent_diagnosis": "Delayed server-to-server webhook arrived 4 minutes after front-end timeout.",
        "agent_action": "Autonomous reconciliation engine matched delayed capture payload; automatically transitioned case to RECOVERED.",
    },
    "UNKNOWN_FAILURE": {
        "id": "UNKNOWN_FAILURE",
        "name": "Unknown/Unclassified Failure",
        "category": "System",
        "source": "system",
        "step": "payment_authorization",
        "code": "GATEWAY_ERROR",
        "reason": "unclassified_failure",
        "description": "Failure received without sufficient diagnostic information from payment rail.",
        "base_risk": 80,
        "base_prob": 0.50,
        "strategy": "Heuristic Deep Scan & Fallback Retry",
        "retry_delay_seconds": 1800,
        "alternate_method": "SMART_LINK",
        "agent_diagnosis": "Rail returned unmapped status code. Ingested raw gateway payload for telemetry learning.",
        "agent_action": "Dispatched smart multi-channel recovery link allowing customer to choose any verified payment method.",
    },
}


def get_failure_profile(failure_reason: str) -> Dict[str, Any]:
    """Retrieve full failure profile by key or fallback to UNKNOWN_FAILURE."""
    if not failure_reason:
        return FAILURE_TAXONOMY["UNKNOWN_FAILURE"]
    clean_key = failure_reason.strip().upper()
    return FAILURE_TAXONOMY.get(clean_key, FAILURE_TAXONOMY["UNKNOWN_FAILURE"])


def generate_gateway_failure_payload(
    failure_reason: str,
    payment_id: str,
    order_id: Optional[str] = None,
    amount: Optional[float] = None,
    method: Optional[str] = None,
    **kwargs
) -> Dict[str, Any]:
    """
    Generate realistic Razorpay production-grade error payload and telemetry.
    """
    profile = get_failure_profile(failure_reason)
    error_dict = {
        "code": profile.get("code", "GATEWAY_ERROR"),
        "description": profile.get("description", "Payment authorization declined"),
        "source": profile.get("source", "bank"),
        "step": profile.get("step", "payment_authorization"),
        "reason": profile.get("reason", "payment_failed"),
        "metadata": {
            "payment_id": payment_id,
            "order_id": order_id or f"order_{payment_id}",
            "failure_cause": profile.get("name", failure_reason),
            "category": profile.get("category", "Gateway"),
            "amount": amount,
            "method": method,
        }
    }
    return {
        "error": error_dict,
        "error_code": profile.get("code", "GATEWAY_ERROR"),
        "error_description": profile.get("description", "Payment authorization declined"),
        "error_source": profile.get("source", "bank"),
        "error_step": profile.get("step", "payment_authorization"),
        "bank_error_code": profile.get("reason", "91"),
        "base_risk": profile.get("base_risk", 75),
        "base_prob": profile.get("base_prob", 0.85),
    }


generate_razorpay_error_payload = generate_gateway_failure_payload

