import enum


class EventType(str, enum.Enum):
    # Payments
    PAYMENT_CREATED = "PAYMENT_CREATED"
    PAYMENT_FAILED = "PAYMENT_FAILED"

    # Recovery Case Lifecycle
    RECOVERY_CASE_CREATED = "RECOVERY_CASE_CREATED"
    RECOVERY_CASE_UPDATED = "RECOVERY_CASE_UPDATED"

    # AI Agent Progression
    AGENT_STARTED = "AGENT_STARTED"
    AGENT_PROGRESS = "AGENT_PROGRESS"
    AGENT_COMPLETED = "AGENT_COMPLETED"

    # Diagnosis & Strategy
    ROOT_CAUSE_IDENTIFIED = "ROOT_CAUSE_IDENTIFIED"
    STRATEGY_SELECTED = "STRATEGY_SELECTED"

    # Policy Evaluation
    POLICY_EVALUATED = "POLICY_EVALUATED"
    POLICY_APPROVED = "POLICY_APPROVED"
    POLICY_BLOCKED = "POLICY_BLOCKED"

    # Intervention Execution
    ACTION_STARTED = "ACTION_STARTED"
    ACTION_COMPLETED = "ACTION_COMPLETED"

    # Outcomes & State Transitions
    RECOVERY_SUCCESS = "RECOVERY_SUCCESS"
    RECOVERY_FAILED = "RECOVERY_FAILED"
    CASE_ESCALATED = "CASE_ESCALATED"
    CASE_STOPPED = "CASE_STOPPED"
